### ISSUE TITLE
Please add some build instructions

### ISSUE THREAD

**Issue by mickeyl** [rusoku/QtSerialBus#1]
`cmake` bails out with:

```
CMake Error at CMakeLists.txt:38:
  Parse error.  Function missing ending ")".  End of file reached.
```

Removing the outcommented line with `#can_api.h)` to fix this, but it still fails with:

```
CMake Error at CMakeLists.txt:53 (if):
  if given arguments:

    "STREQUAL" "Debug"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
```

Removed all that, then I got:

```
ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.8_3/lib/QtSerialBus.framework/QtSerialBus, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.8_3/lib/QtCore.framework/QtCore, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

Adjusted for my architecture by editing `set(CMAKE_OSX_ARCHITECTURES x86_64)` to `set(CMAKE_OSX_ARCHITECTURES arm64)`

Now where am I supposed to put the resulting `.dylib`? Ok, found it in `/opt/homebrew/Cellar/qt@5/5.15.8_3/plugins/canbus`, so I copied it over.

It appears as a valid destination now, but… it doesn't seem to do anything. The controller LEDs stay red.

Any idea what could be wrong?

**Comment by rusoku** [comment]
use Qt5.15.2 branch

**Comment by rusoku** [comment]
#edit this string depends where your QT frameworks is installed
set(CMAKE_PREFIX_PATH "~/Qt/5.15.2/clang_64")

#to compille
cmake -DCMAKE_BUILD_TYPE=Release  -B./release
cmake --build ./release --target clean -v
cmake --build ./release --target all -v

**Comment by mickeyl** [comment]
I see. It might be obvious to you, but for all others: Remember that this plugin dynamically uses the `libUVCANTOU.dylib`, so you must have build it and installed it somewhere `dlopen` will search for... At first I thought it was a self-contained plugin, but of course it makes sense to use the existing Mac-Can-based driver.
